### ISSUE TITLE
Stacked icons

### ISSUE THREAD

**Issue by lfridael** [martndemus/ember-cli-font-awesome#4]
http://fortawesome.github.io/Font-Awesome/examples/#stacked

**Comment by marcemira** [comment]
any news on this feature?

**Comment by lfridael** [comment]
No news on this. I won't get round to implementing this feature myself. I'd be happy to accept a PR if someone feels like taking up the task.

**Comment by martndemus** [comment]
Closing, this is not really simple to implement with how ember currently works. Will accept a PR if someone can implement this cleanly.
