### ISSUE TITLE
Defining action on icon component

### ISSUE THREAD

**Issue by igorpreston** [martndemus/ember-cli-font-awesome#40]
Hello,

I have been using font-awesome in my ember app as main icon library and according to specifics of my project, I have been defining actions on icons that should occur upon click, like so:
```
<i class="fa fa-user" {{action 'iconClicked"}}></i>
```

I want to use ember-cli-font-awesome in my app, but how do I define the action on component like above?

Thanks.

**Comment by lfridael** [comment]
You can't attach an action to the generated `<i>` element, but you can define an action on, for example, a containing `<a>` element.

```hbs
<a href="#" {{action 'doSomething'}}>
{{fa-icon 'star'}}
</a>
```

**Comment by martndemus** [comment]
These are now possible (from version `1.0.0`) through closure actions.

```hbs
{{fa-icon icon="star" click=(action "myClickHandlingAction")}}
```
