### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by BenjaminHorn** [martndemus/ember-cli-font-awesome#71]
After updating Ember CLI to 2.4.0 

DEBUG: -------------------------------
DEBUG: Ember      : 2.4.1
DEBUG: Ember Data : 2.4.0+9f8c40927a
DEBUG: jQuery     : 2.2.1
DEBUG: ------------------------------

In Chrome Inspector's console I am getting (edit: same in Firefox):

> Failed to decode downloaded font: http://localhost:4200/fonts/fontawesome-webfont.woff2?v=4.5.0
> OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
> Failed to decode downloaded font: http://localhost:4200/fonts/fontawesome-webfont.woff?v=4.5.0
> OTS parsing error: incorrect file size in WOFF header
> Failed to decode downloaded font: http://localhost:4200/fonts/fontawesome-webfont.ttf?v=4.5.0
> OTS parsing error: incorrect entrySelector for table directory

And the icons do not appear.

![image](https://cloud.githubusercontent.com/assets/5570232/13443218/75a26bbe-e000-11e5-81a6-d8b88adfbf82.png)

**Comment by martndemus** [comment]
This is an issue with Ember CLI: https://github.com/ember-cli/ember-cli/issues/5538

**Comment by BenjaminHorn** [comment]
thanks!
